# remote linux
remote:
  username: root
  password: qwertyui
  port: 22
  hostname: 1.1.1.1
  directory: /root/xxx


# remote ftp
ftp:
  host: 2.2.2.2
  port: 21
  username: ftp_test
  password: 12323456456
  remoteDirectory: /atom

server:
  port: 9527

# MyBatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.atom.watchremotefile.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.1.1.1:3306/atom_db
    username: root
    password: 213456fds